name: Release CI

on:
  push:
    branches:
      - "develop"
      - "beta"
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v1

      - name: 'Setup Node'
        uses: actions/setup-node@v1

      - name: 'Build Project'
        run: npm run build

      - name: 'Create zip'
        working-directory: ./dist
        run: zip -r "GW2-Startup-Script.zip" "."

      - name: 'Install CI-Tools'
        run: sudo npm install -g @process-engine/ci_tools@latest

      - name: 'Prepare Version'
        run: ci_tools prepare-version --allow-dirty-workdir

      - name: 'Commit & tag version'
        env:
          GH_USER: ${{ secrets.GH_CI_USER_NAME }}
          GH_TOKEN: ${{ secrets.GH_CI_USER_TOKEN }}
        run: ci_tools commit-and-tag-version --only-on-primary-branches

      - name: 'Create github release'
        env:
          GH_USER: ${{ secrets.GH_CI_USER_NAME }}
          GH_TOKEN: ${{ secrets.GH_CI_USER_TOKEN }}
        run: |
          ci_tools update-github-release --only-on-primary-branches --use-title-and-text-from-git-tag
          ci_tools update-github-release --only-on-primary-branches --assets dist/GW2-Startup-Script.zip
