name: Test Release CI

on:
  push:
    branches:
      - "feature/*"
      - "hotfix/*"
      - "release/*"

jobs:
  release:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v1

      - name: 'Setup ps2exe'
        working-directory: ./PS2EXE
        run: Install-Module -Scope CurrentUser -Force ps2exe

      - name: 'Install CI-Tools'
        run: npm install -g @process-engine/ci_tools@latest

      - name: 'Prepare Version'
        run: ci_tools prepare-version --allow-dirty-workdir

      - name: 'Build Project'
        run: npm run build

      - name: 'Create exe'
        shell: powershell -Version 4.0 {0}
        working-directory: ./src
        run: ps2exe -IconFile GW2.ico -InputFile GW2.ps1 -OutputFile "../dist/GW2 Startup Script.exe" -title "GW2 Startup Script" -version ${require('../package.json').version}

      - name: 'Create zip'
        working-directory: ./dist
        run: Compress-Archive "./*" "GW2-Startup-Script.zip"

      - name: 'Print Result'
        working-directory: ./dist
        shell: bash
        run: echo "$(ls -aR)"
