name: Test Release CI

on:
  push:
    branches:
      - "feature/*"
      - "hotfix/*"
      - "release/*"

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v1

      - name: 'Setup Node'
        uses: actions/setup-node@v1

      - name: 'Build Project'
        run: npm run build

      - name: 'Create zip'
        working-directory: ./dist
        run: zip -r "GW2-Startup-Script.zip" "."

      - name: 'Install CI-Tools'
        run: sudo npm install -g @process-engine/ci_tools@latest

      - name: 'Prepare Version'
        run: ci_tools prepare-version --allow-dirty-workdir
